### ISSUE TITLE
[Update Request] Updating to 1.16.3?

### ISSUE THREAD

**Issue by Abbanon** [rdvdev2/DisableCustomWorldsAdvice#1]
Issue title says it all, just curious if you'd consider doing a 1.16.3 update. 
As of right now the initial 1.16.2 release refuses to work for 1.16.3.

**Comment by rdvdev2** [comment]
Right now I'm very busy, but maybe tomorrow I can find some time to try to do a port!

**Comment by alxpettit** [comment]
tested and this mod is very easy to get working on 1.16.3 -- please see my pull req: alxpettit:alxpettit-patch-1.16.3

**Comment by alxpettit** [comment]
Hey @Abbanon,

We're currently discussing best practice for version metadata on the PR. In the meantime you can use my unofficial patched version:
[DisableCustomWorldsAdvice-1.0-UNOFFICIAL-1.16.3-patch.zip](https://github.com/rdvdev2/DisableCustomWorldsAdvice/files/5345666/DisableCustomWorldsAdvice-1.0-UNOFFICIAL-1.16.3-patch.zip)

**Comment by rdvdev2** [comment]
Fixed with #2 and 6bc0aad, check out the new release 1.1 on GitHub releases and Curseforge (when approved).
