### ISSUE TITLE
[MC UPDATE] 1.20.4 compatibility

### ISSUE THREAD

**Issue by glacialvitality** [rdvdev2/DisableCustomWorldsAdvice#14]
- Affected Minecraft version(s): 1.20.4
- Does the game load? N
- Does the game crash when creating a world? N
- Does the game crash when loading a world? Y

**Other information**
Here you can include other information relevant to solving the issue

Crash Log:

[crash-2023-12-12_21.42.58-client.txt](https://github.com/rdvdev2/DisableCustomWorldsAdvice/files/13655277/crash-2023-12-12_21.42.58-client.txt)

**Comment by naritanara** [comment]
Looks like the code that this mod modifies has changed. I'll try to get this working again this week, but no promises as I'm really busy.

**Comment by naritanara** [comment]
Release 5.0 adds 1.20.4 support. Closing.
