### ISSUE TITLE
[MC UPDATE] 1.21.1 compatibility

### ISSUE THREAD

**Issue by SussyBob** [rdvdev2/DisableCustomWorldsAdvice#18]
- Affected Minecraft version(s): 1.21.1
- Does the game load? N
- Does the game crash when creating a world? Y
- Does the game crash when loading a world? Y

**Comment by naritanara** [comment]
I forgot to mark the mod as compatible for 1.21.1-1.21.3 in Modrinth and Curseforge. Reopen this issue if the problems persist, with a detailed step by step to reproduce your problem and the logs of the game.
