### ISSUE TITLE
Make it work with Jitpack, or provide it on maven otherwise

### ISSUE THREAD

**Issue by valoeghese** [rdvdev2/DisableCustomWorldsAdvice#6]
I wanted to use jitpack to include this in a dev workspace

Problem: jitpack craps itself on modern java unless you add jitpack.yml to configure java

**Comment by naritanara** [comment]
I'm currently not able to work on this (university exams) but if you send a PR with the needed changes for jitpack I can review it and potentially merge it.

**Comment by naritanara** [comment]
The mod is available on the Modrinth Maven. Check out its [documentation](https://docs.modrinth.com/docs/tutorials/maven/#tldr) for more information.
