### ISSUE TITLE
1.18.2 incompatibility

### ISSUE THREAD

**Issue by PweSol** [rdvdev2/DisableCustomWorldsAdvice#7]
Crashes. Needs to be updated to 1.18.2

**Comment by devpelux** [comment]
Try this as workaround: [DisableCustomWorldsAdvice-1.18.2.zip](https://github.com/rdvdev2/DisableCustomWorldsAdvice/files/8191616/DisableCustomWorldsAdvice-1.18.2.zip)

This is a patched version that works for 1.18.2.

**Comment by naritanara** [comment]
Working on a fix right now, expect a new release today!

**Comment by naritanara** [comment]
Fixed in version 2.0, you can download it in:
- CurseForge: https://www.curseforge.com/minecraft/mc-mods/fabric-disable-custom-worlds-advice/files/3677546
- Modrinth: https://modrinth.com/mod/dcwa/version/2.0
- GitHub Releases: https://github.com/rdvdev2/DisableCustomWorldsAdvice/releases/tag/v2.0
