### ISSUE TITLE
1.19 compatibility

### ISSUE THREAD

**Issue by espartia** [rdvdev2/DisableCustomWorldsAdvice#8]
# Compatibility with Minecraft 1.19
Currently, this mod is not compatible with 1.19.
## Additional Information
Based on what I have found, the variable that needs to be changed for this mod to work seems to have moved to a new class, `net.minecraft.server.integrates.IntegratedServerLoader` method `start(Screen, String, Boolean, Boolean)`

**Comment by naritanara** [comment]
Working on this right now

**Comment by naritanara** [comment]
Just posted the new release, thanks for the help finding where the relevant conde moved!

You can get the update on:
- [CurseForge](https://www.curseforge.com/minecraft/mc-mods/fabric-disable-custom-worlds-advice/files/3827588) (it may take some time to be publicly available)
- [Modrinth](https://modrinth.com/mod/dcwa/version/3.0)
- [GitHub Releases](https://github.com/rdvdev2/DisableCustomWorldsAdvice/releases/tag/v3.0)
